# This file was generated by GoReleaser. DO NOT EDIT.
cask "shopware-cli" do
  name "shopware-cli"
  desc "Shopware CLI helps Shopware developers manage extensions"
  homepage "https://shopware.com"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shopware-cli"
  bash_completion "completions/shopware-cli.bash"
  zsh_completion "completions/shopware-cli.zsh"
  fish_completion "completions/shopware-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/shopware/shopware-cli/releases/download/#{version}/shopware-cli_Darwin_x86_64.tar.gz"
      sha256 "93663ca5a1412684696732f62b280dd681149838c11a3ee40d26ad15c347cb52"
    end
    on_arm do
      url "https://github.com/shopware/shopware-cli/releases/download/#{version}/shopware-cli_Darwin_arm64.tar.gz"
      sha256 "e746533b3ed535b6ec2c3b460f6eef40991555e71d65177723781edc5ca91b00"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shopware/shopware-cli/releases/download/#{version}/shopware-cli_Linux_x86_64.tar.gz"
      sha256 "8d4aa5b49d8df143a61d9bb07bad99b36746482865410d2616b0246fb5d04c5c"
    end
    on_arm do
      url "https://github.com/shopware/shopware-cli/releases/download/#{version}/shopware-cli_Linux_arm64.tar.gz"
      sha256 "2a7f2630b7a47c3bf512243494350d6d31fe4e78eb93ef71efc74e7c6ab77dfe"
    end
  end

  # No zap stanza required
end
