# This file was generated by GoReleaser. DO NOT EDIT.
cask "shopware-cli" do
  version "0.16.8"

  on_macos do
    on_intel do
      sha256 "d3d95ae158eea6b70805168a383a2638809b2904e855e60ba45bc6efc32144a1"
      url "https://github.com/shopware/shopware-cli/releases/download/#{version}/shopware-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e806500f0631ca5fdf30dd17b85f5e8281f3eda3cab427c2074239c2f17dba04"
      url "https://github.com/shopware/shopware-cli/releases/download/#{version}/shopware-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d4ffebfc7877bfae8b4e0c87c9fa94201532fea9525821e77beeff73455e2b9"
      url "https://github.com/shopware/shopware-cli/releases/download/#{version}/shopware-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "857092f28b94e003ce4a1ef1e30a441c358b79e2beb2761105b0964ebc3f5955"
      url "https://github.com/shopware/shopware-cli/releases/download/#{version}/shopware-cli_Linux_arm64.tar.gz"
    end
  end

  name "shopware-cli"
  desc "Shopware CLI helps Shopware developers manage extensions"
  homepage "https://shopware.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shopware-cli"
  bash_completion "completions/shopware-cli.bash"
  fish_completion "completions/shopware-cli.fish"
  zsh_completion "completions/shopware-cli.zsh"

  postflight do
    system_command "/bin/ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/shopware-cli", "#{HOMEBREW_PREFIX}/bin/swx"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/swx"]
  end

  # No zap stanza required

end
