# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategies"
class DashyCli < Formula
  desc ""
  homepage ""
  version "0.0.9-dev"
  license "Closed Source"

  on_macos do
    on_intel do
      url "https://github.com/shopware/dashy-cli/releases/download/v0.0.9-dev/dashy-cli_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "95f276e0e6d8e485a3d941fd11534dea921cc25cb567c9672c313791793a3edf"

      def install
        bin.install "dashy"
        bash_completion.install "completions/dashy.bash" => "_dashy"
        zsh_completion.install "completions/dashy.zsh" => "_dashy"
        fish_completion.install "completions/dashy.fish"
      end
    end
    on_arm do
      url "https://github.com/shopware/dashy-cli/releases/download/v0.0.9-dev/dashy-cli_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "62b5c7df3dbb293f2a94f659d05974d15ffeab311a2534e60f7661c02eab7c1e"

      def install
        bin.install "dashy"
        bash_completion.install "completions/dashy.bash" => "_dashy"
        zsh_completion.install "completions/dashy.zsh" => "_dashy"
        fish_completion.install "completions/dashy.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shopware/dashy-cli/releases/download/v0.0.9-dev/dashy-cli_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "2ca4577706de9c366c35b481dc1183a7cc7d5ae91d7d07fe4ff00ab8b0fd9ab4"

        def install
          bin.install "dashy"
          bash_completion.install "completions/dashy.bash" => "_dashy"
          zsh_completion.install "completions/dashy.zsh" => "_dashy"
          fish_completion.install "completions/dashy.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shopware/dashy-cli/releases/download/v0.0.9-dev/dashy-cli_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "091d6280f2488c3427c1708e552e5c7fe53c92a609120c2c0ddacb6799a5110e"

        def install
          bin.install "dashy"
          bash_completion.install "completions/dashy.bash" => "_dashy"
          zsh_completion.install "completions/dashy.zsh" => "_dashy"
          fish_completion.install "completions/dashy.fish"
        end
      end
    end
  end
end
