# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategies"
class DashyCli < Formula
  desc ""
  homepage ""
  version "0.0.13-dev"
  license "Closed Source"

  on_macos do
    on_intel do
      url "https://github.com/shopware/dashy-cli/releases/download/v0.0.13-dev/dashy-cli_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c8bdbab03e18b36d8dac933048efa6213eb9ce1798e9da83de44ecb821f3f19f"

      def install
        bin.install "dashy"
        bash_completion.install "completions/dashy.bash" => "_dashy"
        zsh_completion.install "completions/dashy.zsh" => "_dashy"
        fish_completion.install "completions/dashy.fish"
      end
    end
    on_arm do
      url "https://github.com/shopware/dashy-cli/releases/download/v0.0.13-dev/dashy-cli_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c2df8a76029f851e78d0882b98c6eef914a8124557111c326dbe0f4ccbc5b155"

      def install
        bin.install "dashy"
        bash_completion.install "completions/dashy.bash" => "_dashy"
        zsh_completion.install "completions/dashy.zsh" => "_dashy"
        fish_completion.install "completions/dashy.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shopware/dashy-cli/releases/download/v0.0.13-dev/dashy-cli_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "059d5f01354cfe63828e39cee893322e625004da407aab5255db0729d0996c0b"

        def install
          bin.install "dashy"
          bash_completion.install "completions/dashy.bash" => "_dashy"
          zsh_completion.install "completions/dashy.zsh" => "_dashy"
          fish_completion.install "completions/dashy.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shopware/dashy-cli/releases/download/v0.0.13-dev/dashy-cli_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "66e9ff0a257e616c83ff54f40c04d1b5b03009a01f9066b394931eb7f0a626b8"

        def install
          bin.install "dashy"
          bash_completion.install "completions/dashy.bash" => "_dashy"
          zsh_completion.install "completions/dashy.zsh" => "_dashy"
          fish_completion.install "completions/dashy.fish"
        end
      end
    end
  end
end
