# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopwareLsp < Formula
  desc "Shopware Language Server"
  homepage "https://shopware.com"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shopwareLabs/shopware-lsp/releases/download/0.0.12/shopware-lsp_0.0.12_darwin_amd64.zip"
      sha256 "72f914a1e6b5df87b4c5293656dec97671eb7d6aba51a3d2989d323319b7ed95"

      def install
        bin.install "shopware-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shopwareLabs/shopware-lsp/releases/download/0.0.12/shopware-lsp_0.0.12_darwin_arm64.zip"
      sha256 "3dd4b884eefb8012a03d42d845a8fc9f90b00a16ffbc72f5615d06bae6173f57"

      def install
        bin.install "shopware-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shopwareLabs/shopware-lsp/releases/download/0.0.12/shopware-lsp_0.0.12_linux_amd64.zip"
      sha256 "058f17d100bc1e344cf010c663b64a5ad5677d39d3d19c9b965acc8a36c882b7"
      def install
        bin.install "shopware-lsp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shopwareLabs/shopware-lsp/releases/download/0.0.12/shopware-lsp_0.0.12_linux_arm64.zip"
      sha256 "7bf3e5da0ab7bc852ca6dee1eb20188ec57b43b527c27d3b86a93fbdec1cfe27"
      def install
        bin.install "shopware-lsp"
      end
    end
  end
end
