# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopwareLsp < Formula
  desc "Shopware Language Server"
  homepage "https://shopware.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shopwareLabs/shopware-lsp/releases/download/0.1.0/shopware-lsp_0.1.0_darwin_amd64.zip"
      sha256 "c6246e5c380adc0434edb7e655dc0fec516bfab4c8dc1249f7c6016ac66bbaf9"

      def install
        bin.install "shopware-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shopwareLabs/shopware-lsp/releases/download/0.1.0/shopware-lsp_0.1.0_darwin_arm64.zip"
      sha256 "2286cea4b9fbcd0b658ac891a79ab70647f9124f8a92a0ec1ad906a2fe3ff772"

      def install
        bin.install "shopware-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopwareLabs/shopware-lsp/releases/download/0.1.0/shopware-lsp_0.1.0_linux_amd64.zip"
      sha256 "6d676aa6b9757e964c95ec661f576e7270865a2fefcc8051b35180e9d594a069"
      def install
        bin.install "shopware-lsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopwareLabs/shopware-lsp/releases/download/0.1.0/shopware-lsp_0.1.0_linux_arm64.zip"
      sha256 "821fa7eeeb5225bada8e16fb90b7c3257b668a745c2a2a10436fc068d048fdf7"
      def install
        bin.install "shopware-lsp"
      end
    end
  end
end
