# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopwareLsp < Formula
  desc "Shopware Language Server"
  homepage "https://shopware.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shopware/shopware-lsp/releases/download/0.1.2/shopware-lsp_0.1.2_darwin_amd64.zip"
      sha256 "c1d167ae1d50c51f5c2ae5818cdb821f80814f5f054fbc33d26f78920590f9c3"

      define_method(:install) do
        bin.install "shopware-lsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shopware/shopware-lsp/releases/download/0.1.2/shopware-lsp_0.1.2_darwin_arm64.zip"
      sha256 "a34595581820de22ce412e17c0b88324729a7f06606138fb1bfbf42a8ba5f5b3"

      define_method(:install) do
        bin.install "shopware-lsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopware/shopware-lsp/releases/download/0.1.2/shopware-lsp_0.1.2_linux_amd64.zip"
      sha256 "8f0ec5f279f2b7d87d451c557a0f445eea89e2f5100e6d8007f67302ed38fb8d"
      define_method(:install) do
        bin.install "shopware-lsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopware/shopware-lsp/releases/download/0.1.2/shopware-lsp_0.1.2_linux_arm64.zip"
      sha256 "55d9760ad57d97a41b9144e36ea0ccdb86c5ae60764e28c35e0195e79b5de0d4"
      define_method(:install) do
        bin.install "shopware-lsp"
      end
    end
  end
end
