# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategies"
class SwPaas < Formula
  desc ""
  homepage ""
  version "0.0.48"
  license "Closed Source"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shopware/paas-cli/releases/download/0.0.48/sw-paas_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "baf003d79d1fb6a82a452f0c410ab9952d6b78e7325cf2faccecc34ecb939be7"

      define_method(:install) do
        bin.install "sw-paas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shopware/paas-cli/releases/download/0.0.48/sw-paas_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "98a417a9569f442e6b4a7ff8ff8caf0d7f40f3c3a8d775db3d4dfb9338bbe4fe"

      define_method(:install) do
        bin.install "sw-paas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopware/paas-cli/releases/download/0.0.48/sw-paas_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1b00cc950936d4cc4b8ceab70818bc0ba94f2987713edf0121ec2729b74b0f9b"
      define_method(:install) do
        bin.install "sw-paas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shopware/paas-cli/releases/download/0.0.48/sw-paas_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7d51c93e177d2d5a2a9f136607151084c6e7076d59fcff03701b5a86de9355f0"
      define_method(:install) do
        bin.install "sw-paas"
      end
    end
  end
end
