issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopwareLabs/shopware-lsp:ref:refs/tags/[0-9]+\.[0-9]+\.[0-9]+
claim_pattern:
  job_workflow_ref: shopwareLabs/shopware-lsp/.github/workflows/release.yml@refs/tags/[0-9]+\.[0-9]+\.[0-9]+

permissions:
  contents: write
