issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/paas-cli:ref:refs/tags/[0-9]+\.[0-9]+\.[0-9]+
claim_pattern:
  job_workflow_ref: shopware/paas-cli/.github/workflows/release-tag.yaml@refs/tags/[0-9]+\.[0-9]+\.[0-9]+

permissions:
  contents: write
